### ISSUE TITLE
Error saving data to InfluxDB

### ISSUE THREAD

**Issue by lars-magne** [influxdata/influxdb.com#559]
Hello,
We use InfluxDB to collect sensordata from Mosquitto in NodeJS using the 'influx' library.  NodeJS simply forward data from Mosquitto to InfluxDB.
The problem occurs if the mobile link to some sensors has been down for a while and the sensors send a bunch of values when the link is back.  Then we loose many samples and the log is filled up with errors like these:
...
Error saving data to InfluxDB! Error: Request timed out
    at ServiceNotAvailableError.Error (native)
    at new ServiceNotAvailableError (/usr/embilink/node_modules/influx/lib/src/pool.js:37:28)
    at /usr/embilink/node_modules/influx/lib/src/pool.js:286:38
    at ClientRequest.<anonymous> (/usr/embilink/node_modules/influx/lib/src/pool.js:79:13)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitRequestTimeout (_http_client.js:566:42)
    at Socket.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
...

Any idea what can cause this?

Regards
Lars Magne

**Comment by srinivasrk** [comment]
Hi, did you find out what caused this?

**Comment by stevenhaslam** [comment]
Hello,

I too am observing a similar error when inserting data into InfluxDB using Node Red:

Error: Internal Server Error
    at ServiceNotAvailableError.Error (native)
    at new ServiceNotAvailableError (/data/node_modules/influx/lib/src/pool.js:37:28)
    at /data/node_modules/influx/lib/src/pool.js:272:49
    at ClientRequest.<anonymous> (/data/node_modules/influx/lib/src/pool.js:79:13)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:478:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:367:20)


As reported above if the load within a time-window exceeds some threshold InfluxDB reports these errors and we are forced to restart the process.  We have tried batching the data to creating a basic throttle but we still observe the issue.  Currently we are prevented from inserting larger volumes of data into InfluxDB and this is making us revisit Influx's suitability for larger scale implementations.  Since we like the features Influx offers (in particular when coupled with Grafana and Node Red) we are hoping others have encountered this issue and have some insight how to alleviate it (e.g. configuration).

Thank you in advance.

Regards,
Steven
